### ISSUE TITLE
Requires non-exported function guide_axis from ggplot2

### ISSUE THREAD

**Issue by sorrywm** [ashenoy-cmbi/grafify#1]
I am having difficulty plotting with grafify due to the call to `guide_axis`, which it appears from here is only an internal function in ggplot2:
[](https://github.com/tidyverse/ggplot2/blob/master/R/guides-axis.r)
Here is the error message:
Error in guide_axis(angle = { : could not find function "guide_axis"

Is the appropriate recourse to copy the function from ggplot?

**Comment by ashenoy-cmbi** [comment]
Hi sorrywm,
guide_axis is a function in ggplot2 that is called by the "TextAngle" argument. I was not able to replicate that error and am able to set the angle and get axis labels to rotate. I'm using ggplot2 v3.3.5 on RStudio v1.4.1717 and R v4.1.0. 
Best wishes,
Avinash

 
> I am having difficulty plotting with grafify due to the call to `guide_axis`, which it appears from here is only an internal function in ggplot2:
> 
> Here is the error message:
> Error in guide_axis(angle = { : could not find function "guide_axis"
> 
> Is the appropriate recourse to copy the function from ggplot?

**Comment by ashenoy-cmbi** [comment]
This works for example,
plot_scatterbox(data_t_pdiff, Condition, Mass)+guides(x = guide_axis(angle = 90))


> Hi sorrywm,
> guide_axis is a function in ggplot2 that is called by the "TextAngle" argument. I was not able to replicate that error and am able to set the angle and get axis labels to rotate. I'm using ggplot2 v3.3.5 on RStudio v1.4.1717 and R v4.1.0.
> Best wishes,
> Avinash
> 
> > I am having difficulty plotting with grafify due to the call to `guide_axis`, which it appears from here is only an internal function in ggplot2:
> > Here is the error message:
> > Error in guide_axis(angle = { : could not find function "guide_axis"
> > Is the appropriate recourse to copy the function from ggplot?
