### ISSUE TITLE
Allow option to color/fill by another variable

### ISSUE THREAD

**Issue by sorrywm** [ashenoy-cmbi/grafify#2]
Hi @ashenoy-cmbi! Is there a way to use `grafify` plotting functions but base the color on a variable that is not the X axis variable? For example, I have a tibble with a column that represents individual tissues that I want to use as the x-axis, and another column that groups those tissues into organs/systems that I would like to use for the colors/fills.  

Thank you for your help!

**Comment by ashenoy-cmbi** [comment]
Hi @sorrywm , not sure I understand clearly, but with 2 grouping variables and a Y variable you should be using `plot_3d..` or `plot_4d..`. In these the fill is assigned by the grouping factor and not the X variable. The fill is assigned by X only in plots with two variables.

**Comment by ashenoy-cmbi** [comment]
Hi @sorrywm , as I haven't heard from you, should I close this issue? You've probably figured it out by now?
Thanks,
Avinash

**Comment by Victoria0017** [comment]
Hi ashenoy-cmbi, 

mpg %>% 
  plot_3d_scatterbox(cyl, hwy, class, s_alpha = 0)

The plot I get:
![Rplot](https://user-images.githubusercontent.com/99631912/176998865-8ed2be97-c2b2-44be-a480-ca07faf8a140.png)

Why I don't get the class variable shown on the graphic?

Thanks very much in advance.

**Comment by ashenoy-cmbi** [comment]
Hi [Victoria0017](https://github.com/Victoria0017), that's because you have set `s_alpha=0`. This sets the transparency of symbols to 100% and they are not seen anymore. The variables will show up if you change this, for example. 
`mpg %>%
plot_3d_scatterbox(cyl, hwy, class, s_alpha = 0.5)`

**Comment by Victoria0017** [comment]
Thank you ashenoy-cmbi.

I use: 
mpg %>% plot_3d_scatterbox(cyl, hwy, class, s_alpha = 0.5)

I get:
![image](https://user-images.githubusercontent.com/99631912/177019846-7a2d06bc-dcb8-47a7-addd-0fb66d47279e.png)

How could I get the graphic like this one:
![image](https://user-images.githubusercontent.com/99631912/177019929-eb537f68-6687-46ae-b4da-82055961b726.png)

Many thanks for your advice.

**Comment by ashenoy-cmbi** [comment]
For this kind of a plot - 2way ANOVA type designs - you'll need to use the `plot_4d_` versions of plot functions
`mpg %>% plot_4d_scatterbox(cyl, hwy, class, class, s_alpha = 0)`

**Comment by Victoria0017** [comment]
Thanks a lot, ashenoy-cmbi.
That works :)
