### ISSUE TITLE
Add P-values and Significance Levels to grafify

### ISSUE THREAD

**Issue by shaoyoucheng** [ashenoy-cmbi/grafify#4]
The level of statistical significance is often expressed as a p -value . How to Calculate P Value and mark Significance Levels to grafify? ggpubr or ggsignif plugin??

Looking Forward to Hearing from You

**Comment by ashenoy-cmbi** [comment]
Hi, simple and mixed effects linear models are available in the package to compare groups, please see the vignette website for details. I'm not planning to add functionality from ggpubr as that can be used on plots made with grafify as well if you want to. 
For example, this code works adds bracketed P value to the plot. 
```{r }
plot_scatterbox(data_t_pratio, Genotype, log(Cytokine))+
ggpubr::stat_compare_means(paired = TRUE, method = "t.test", label.y = 3.5, comparisons = list(c("KO", "WT")))
```

**Comment by shaoyoucheng** [comment]
Thank you for the quick reply.
